config/urls.py
from django.contrib import admin
from django.urls import path, include
from crud import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crud.urls', namespace='crud'))
]

crud/urls.py
from django.urls import path
from . import views

app_name = "crud"
urlpatterns = [
    path('',    views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('edit/<int:editting_id>', views.edit, name='edit'),
]

crud/models.py
from django.db import models

class Message(models.Model):
    message = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u"{0}:{1}...".format(self.id, self.message[:10])

crud/forms.py
from django import forms

class MessageForm(forms.Form):
    message = forms.CharField(
        label='メッセージ',
        max_length=255,
        required=True,
        widget=forms.TextInput()
        )

crud/views.py
from django.shortcuts import ( 
    render, 
    redirect,
    get_object_or_404
     )
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from .models import Message
from .forms import MessageForm 

def index(request):
    d = {
        'messages': Message.objects.all(),
    }
    return render(request, 'crud/index.html', d)

def add(request):
    form = MessageForm(request.POST or None)
    if form.is_valid():
        Message.objects.create(**form.cleaned_data)
        return redirect('crud:index')
    
    d = {
        'form': form,
    }
    return render(request, 'crud/edit.html',d)

def edit(request, editting_id):
    message = get_object_or_404(Message, id=editting_id)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message.message = form.cleaned_data['message']
            message.save()
            return redirect('crud:index')
    else:
        # GETリクエスト時はDBに保存されているデータを表示する
        form = MessageForm({'message': message.message})

    d = {
        'form': form,
    }
    return render(request, 'crud/edit.html', d)

@require_POST
def delete(request):
    delete_ids = request.POST.getlist("delete_ids")
    if delete_ids:
        Message.objects.filter(id__in=delete_ids).delete()
    return redirect('crud:index')

templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/crud/edit.html
{% extends "base.html" %}

{% block body %}
<a href="{% url 'crud:index' %}">一覧画面へ</a>
<form method="POST" action="">
    {{ form.errors.message }}
    <label>{{ form.message.label }}{{ form.message }}</label><br />
    {% csrf_token %}
    <input type="submit" value="登録" />
</form>
{% endblock %}

templates/crud/index.html
{% extends "base.html" %}

{% block body %}
    <a href="{% url 'crud:add' %}">登録画面へ</a>
    <form method="POST" action="{% url 'crud:delete' %}">
        <table style="border: solid 1px;">
            <thead>
                <tr>
                    <th>message</th>
                    <th>created_at</th>
                    <th>updated_at</th>
                    <th>  </th>
                </tr>
            </thead>
            <tbody>
                {% for message in messages %}
                    <tr>
                        <td><input type="checkbox" name="delete_ids" value="{{ message.id }}"/></td>
                        <td>{{ message.message }}</td>
                        <td>{{ message.created_at }}</td>
                        <td>{{ message.updated_at }}</td>
                        <td><a href="{% url 'crud:edit' message.id %}">更新画面へ</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <input type="submit" value="削除" />
    </form>
{% endblock %}